# Permalinks
permalink:        date
#relative_permalinks: true

# Setup
title:            'Oles Neugier- Tagebuch'
description:      'Ein Blog spezialisiert auf das, was dich und mich interessiert und neugierig macht...'

url:              https://speedynurbesser.github.io
baseurl:          "/"

author:
  name:           'Ole'



# Custom vars

github:
  repo:           https://github.com/SpeedyNurBesser/myBlog
